drop table if exists users_in_activities;
drop table if exists activities;
drop table if exists users;


create table "users"
(
    id   integer generated by default as identity,
    name varchar
);

alter table users add constraint users_pk primary key (id);

create table "activities"
(
    id   integer generated by default as identity,
    points int,
    name varchar,
    status varchar,
    location point not null,
    creator_id int not null,
    performer_id int
);

alter table activities add constraint activities_pk primary key (id);

alter table activities
    add constraint creator_fk
        foreign key (creator_id) references users;

alter table activities
    add constraint performer_fk
        foreign key (performer_id) references users;
