drop table if exists users_in_activities;
drop table if exists activities;
drop table if exists users;


create table "users"
(
    id   integer generated by default as identity,
    name varchar
);

alter table users add constraint users_pk primary key (id);

create table "activities"
(
    id   integer generated by default as identity,
    points int,
    name varchar
);

alter table activities add constraint activities_pk primary key (id);


create table users_in_activities
(
    user_id     int
        constraint user_fk
            references users (id),
    activity_id int
        constraint activity_fk
            references activities (id)
);
